[project]
name = "kart-machine-manager"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "Oryomei", email = "o.ryomei1020@gmail.com" }]
dependencies = [
    "python-can>=4.3.1",
    "pyqt6>=6.7",
    "python-dotenv>=1.0.1",
    "requests>=2.31.0",
]
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = ["mypy>=1.9.0", "ruff>=0.4.1"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.mypy]

[[tool.mypy.overrides]]
module = "requests"
ignore_missing_imports = true
