name: Ruff
on:
  push:
    branches: [master, develop, feature/rye]
  pull_request:
    branches: [master, develop]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "./app"
          args: --config ./app/ruff.toml
